spring:
  datasource:
    url: jdbc:postgresql://192.168.106.134:5432/scrapy
    username: postgres
    password: 009314
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

mybatis:
  configuration:
    # 开启下划线到驼峰的自动转换，将数据库字段根据驼峰规则自动注入到对象属性
    map-underscore-to-camel-case: true



student:
  name: pavel.zhang
  age: 23

logging:
  file: myapp.log
  level:
    com.example.demo: debug


